# SwiftLint Configuration for iOS Boilerplate
# Mobile-friendly rules for rapid consumer app development

# Paths to include/exclude
included:
  - iOSBoilerplate

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - iOSBoilerplate.xcodeproj
  - iOSBoilerplate.xcworkspace

# Analyzer rules (require compilation)
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - file_header # Disable for initial development, enable later
  - no_hardcoded_strings # Disable for demo content

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - uri

# File header template (disabled for now)
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*\.swift
#                     \/\/  iOSBoilerplate
#                     \/\/
#                     \/\/  Created by .* on .*\.
#                     \/\/

# Custom rules for mobile development
custom_rules:
  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '(Text|Label|Button|Alert)\s*\(\s*"[^"]*"\s*\)'
    message: "Use localized strings instead of hardcoded text"
    severity: warning
  
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
  
  no_force_unwrapping_in_views:
    name: "No Force Unwrapping in Views"
    regex: '!\s*(?=\s*(\.|\[|\(|$))'
    match_kinds:
      - comment
      - doccomment
      - string
    message: "Avoid force unwrapping in view code, use safe unwrapping or default values"
    severity: warning

# Reporter type
reporter: "xcode"
