name: iOSBoilerplate
options:
  bundleIdPrefix: com.mobirithm
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.0"
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  iOSBoilerplate:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iOSBoilerplate
        excludes:
          - "**/.DS_Store"
    resources:
      - iOSBoilerplate/Resources/**
      - iOSBoilerplate/Preview Content/**
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mobirithm.iOSBoilerplate
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ENABLE_PREVIEWS: true
      DEVELOPMENT_ASSET_PATHS: "\"iOSBoilerplate/Preview Content\""
      GENERATE_INFOPLIST_FILE: true

schemes:
  iOSBoilerplate:
    build:
      targets:
        iOSBoilerplate: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
